### ISSUE TITLE
[FEAT] Move logs to ramdisk

### ISSUE THREAD

**Issue by denics** [NeonGeckoCom/neon-image-recipe#97] opened 2023-05-13 16:24 UTC
### Objective

logs in neon/ovos/mycroft can be quite verbose and usually slow down the system, fill up a whole partition (yes, leave it on all night ;) ) or worst, they fry your SD card.
As by default your image generate a ramdisk that it is never used, it would be nice to move the ovos logs, and why not ALL logs, to the ramdisk partition. This will speed up the system, save the SD/SDD and be reset at every restart.

### Initial Implementation Requirements

- install log2ram
- modify all neon systemd files to log into /var/logs/neon

or

- modify all neon systemd files to log into /ramdisk/neon/logs
- add a dependence on the creation of the ramdisk in systemd

**Comment by denics** [comment] 2023-05-13 17:22
this configuration by default would be a working solution:

```
log_dir: /home/neon/logs/
log_level: WARNING
logs:
  path: /ramdisk/neon/
```

**Comment by NeonDaniel** [comment] 2023-08-28 16:57
Duplicate of https://github.com/NeonGeckoCom/neon_debos/issues/26

**Closed as completed by NeonDaniel** 2023-08-28 16:57 UTC
Labels: enhancement
