### ISSUE TITLE
[BUG] ovos_PHAL_plugin_brightness_control_rpi:discover:123 - ERROR

### ISSUE THREAD

**Issue by denics** [NeonGeckoCom/neon-image-recipe#98] opened 2023-05-13 17:21 UTC
### Description

NeonOS install, correctly and by default, ovos_PHAL_plugin_brightness_control_rpi however, the image does not include the raspberrypi/userland tools generating a 

```ovos_PHAL_plugin_brightness_control_rpi:discover:123 - ERROR - [Errno 2] No such file or directory: '/opt/vc/bin/vcgencmd': '/opt/vc/bin/vcgencmd'```

error.

### Steps to Reproduce

- monitor 'enclosure.log'
- version 23.5.11

**Comment by NeonDaniel** [comment] 2023-08-28 16:59
Duplicate of https://github.com/OpenVoiceOS/ovos-gui-plugin-shell-companion/issues/12

**Closed as completed by NeonDaniel** 2023-08-28 16:59 UTC
Labels: bug
